project:
  title: Analysing spatial data using R

subtitle: Brunei R User Group

toc: true

author:
  - name: Haziq Jamil
    orcid: 0000-0003-3298-1010
    email: haziq.jamil@ubd.edu.bn
    # roles: writing
    corresponding: true
    affiliations:
      - name: Universiti Brunei Darussalam
        # name: Mathematical Sciences, Faculty of Science
        address: Universiti Brunei Darussalam, Jalan Tungku Link
        city: Bandar Seri Begawan
        # state: WA
        postal-code: BE 1410

date-modified: 9 March 2023

fontsize: 120%
