project:
  # title: Analysing spatial data using R
  type: website
  output-dir: _site
  # post-render: 
  #   - extract_code.R

other-links:
  - text: Brunei R website
    href: https://bruneir.github.io

code-links:
  - repo
  - text: R Script
    href: https://raw.githubusercontent.com/bruneir/brm-spatial/main/br-spatial.R

format: 
  html:
    code-fold: true
    code-tools: true
    code-link: true
    # code-line-numbers: true
    toc: true
    toc-title: On this page

last-modified: last-modified

lightbox: true

fontsize: 120%

execute:
  freeze: auto
  warning: false
  # cache: true

knitr: 
  opts_chunk:
    fig.align: center
    out-width: 100%
 
bibliography: ref.bib
nocite: |
  @*