project:
  # title: Analysing spatial data using R
  output-dir: _site

other-links:
  - text: Brunei R website
    href: https://bruneir.github.io

code-links:
  - repo

format: 
  html:
    code-fold: true
    code-tools: true
    code-link: true
    # code-line-numbers: true
    toc: true
    toc-title: On this page

last-modified: last-modified

lightbox: true

fontsize: 120%

execute:
  freeze: auto
  warning: false

knitr: 
  opts_chunk:
    fig.align: center
    out-width: 100%